# Generated by Django 5.1.5 on 2025-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200618_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.AddField(
            model_name='table',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='prefer',
            field=models.CharField(blank=True, choices=[('1', 'definitely'), ('2', 'maybe'), ('3', 'not sure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='purpose',
            field=models.CharField(blank=True, choices=[('1', 'Date'), ('2', 'Birthday'), ('3', 'Anniversary'), ('4', 'Party')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'individual'), ('2', 'couple'), ('3', 'small group'), ('4', 'large group'), ('5', 'prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
